#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Starting data_saver_node"
rosrun data_saver odom_path &
pid="$pid $!"
sleep 5s

roslaunch pioneer_nav2d map_server.launch &
pid="$pid $!"
sleep 5s


rosrun rviz rviz &
pid="$pid $!"
sleep 5s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h

