#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Starting data_saver_node"
for i in `seq 1 1`;
do
  roslaunch data_saver save_topics.launch robot_name:=pioneer$i use_bag:=true &
  pid="$pid $!"
  sleep 5s
done

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h

