#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

roslaunch pioneer_nav2d map_server.launch &
pid="$pid $!"
sleep 5s

echo "Starting data_saver_node"
roslaunch data_saver rosbag.launch &
pid="$pid $!"
sleep 1s


rosrun rviz rviz &
pid="$pid $!"
sleep 5s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h

