#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching goal parameter..."
roslaunch multi_nav goal_point_loader.launch &
pid=$!
sleep 5s

echo "Sending goal to the pioneers"
for i in `seq 1 2`;
do
  roslaunch multi_nav pioneer_goal.launch robot_name:=pioneer$i pose:="-x $(rosparam get /x)+$i -y $(rosparam get /y) -a 0.5*$i" &
  pid="$pid $!"
  sleep 5s
done

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h

