#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!

echo "Launching Gazebo..."
sleep 10s
roslaunch pioneer_gazebo big_maze_pioneer_kinect_no_nodlet.launch &
pid="$pid $!"

echo "Loading fake laser..."
sleep 10s
roslaunch pointcloud_to_laserscan sample_node.launch &
pid="$pid $!"

echo "Loading initialisation parameters..."
sleep 10s
roslaunch pioneer_description pioneer_with_kinect_gazebo.launch &
pid="$pid $!"

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
