#!/bin/bash
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching Sender Goal..."
sleep 10s
roslaunch coords_sender coord_multiple_sender.launch &
pid="$pid $!"

echo "Loading Multi Nav Goal..."
sleep 10s
roslaunch multi_nav send_goals.launch & 
pid="$pid $!"


trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
