#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching pioneer_description..."
roslaunch pioneer_to_goal gabi_description.launch pioneer_model:=multi_pioneer_kinect_real.urdf &
pid="$pid $!"
sleep 5s

echo "Launching map server..."
roslaunch pioneer_to_goal map_server.launch map_name:=institut2 &
pid="$pid $!"
sleep 5s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h

