#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching Gazebo..."
roslaunch pioneer_gazebo pioneer_hokuyo_wold.launch world:=utm_0 &
pid="$pid $!"

sleep 5s

echo "Launching navigation stack..."
roslaunch robotnav_try mapping_bundle.launch &
pid="$pid $!"

sleep 3s


echo "Launching Rviz..."
roslaunch pioneer_description pioneer_hokuyo_sim.launch &
pid="$pid $!"


trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
