#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

for i in `seq 1 1`;
do
  roslaunch pioneer_to_goal gabi_merge_kinect.launch name:=pioneer$i x:="$(rosparam get /pioneer$i/x)" y:="$(rosparam get /pioneer$i/y)" yaw:="$(rosparam get /pioneer$i/a)" &
  pid="$pid $!"
  sleep 5s
done
sleep 5s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h

