#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching Gazebo..."
roslaunch multi_robot multi_robot.launch &
pid="$pid $!"
sleep 5s

echo "Launching Gazebo..."
roslaunch multi_robot multi_robot_navigation.launch &
pid="$pid $!"
sleep 5s

echo "Launching rviz..."
roslaunch robotnav_try multi_pioneer_kinect.launch rviz_config:=two_pioneer_kinect &
pid="$pid $!"
sleep 10s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h

