#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!

echo "Launching Gazebo..."
sleep 10s
roslaunch pioneer_gazebo big_maze_pioneer_kinect.launch &
pid="$pid $!"

echo "Launching Gmapping..."
sleep 10s
roslaunch turtlebot_gazebo gmapping_demo.launch &
pid="$pid $!"

echo "aunching RViz..."
sleep 10s
roslaunch turtlebot_rviz_launchers view_navigation.launch &
pid="$pid $!"

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
