#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching Gazebo..."
roslaunch pioneer_gazebo pioneer_kinect_laserscan_world_choosable.launch world_name:=scout_service &
pid="$pid $!"
sleep 15s

echo "Loading initialisation parameters..."
roslaunch pioneer_description robot_kinect_description.launch pose_file:=pioneer_poses
sleep 10s
echo "Launching Pioneers in Gazebo stack..."
sleep 5s
for i in `seq 1 2`;
do
  roslaunch pioneer_description generic_pioneer.launch name:="pioneer$i" pose:="-x $(rosparam get /pioneer$i/x) -y $(rosparam get /pioneer$i/y) -Y $(rosparam get /pioneer$i/a)" &
  pid="$pid $!"
  sleep 10s
done

for i in `seq 1 2`;
do
  roslaunch laserscan_kinect laserscan_multi_sim.launch name:="pioneer$i" &
  pid="$pid $!"
  sleep 5s
done

echo "Launching map server..."

roslaunch pioneer_nav map_server.launch map_name:=scout_gabi &
pid="$pid $!"
sleep 10s

echo "Launching navigation stack..."
sleep 5s
for i in `seq 1 2`;
do
  roslaunch pioneer_nav single_navigation_kinect.launch robot_name:=pioneer$i x:="$(rosparam get /pioneer$i/x)" y:="$(rosparam get /pioneer$i/y)" yaw:="$(rosparam get /pioneer$i/a)" move_type:="kinect" &
  pid="$pid $!"
  sleep 10s
done

echo "Launching rviz..."
roslaunch pioneer_description multi_pioneer_hokuyo.launch rviz_config:=multi_pioneer &
pid="$pid $!"
sleep 10s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h

