#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching Gazebo..."
roslaunch pioneer_gazebo pioneer_kinect_world1.launch &
pid="$pid $!"
echo "so far so goooooooooood!"
sleep 15s

echo "Launching poincloud to laserscan..."
roslaunch pointcloud_to_laserscan sample_node.launch &
pid="$pid $!"
sleep 10s

echo "Launching gmapping..."
roslaunch pioneer_gazebo gmapping_demo_kinect.launch &
pid="$pid $!"
sleep 10s

echo "Launching RViz..."
roslaunch pioneer_description pioneer_kinect_sim.launch &
pid="$pid $!"
sleep 5s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
