#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching Gazebo..."
roslaunch pioneer_gazebo pioneer_kinect_world_umt_0.launch &
pid="$pid $!"
sleep 15s

echo "Launching poincloud to laserscan..."
roslaunch laserscan_kinect laserscan_sim.launch &
pid="$pid $!"
sleep 10s

echo "Launching gmapping..."
roslaunch pioneer_gazebo gmapping_demo_kinect.launch &
pid="$pid $!"
sleep 10s

echo "Launching controller..."
roslaunch pioneer_ros pioneer_controller_spin_recover.launch &
pid="$pid $!"
sleep 5s

echo "Launching RViz..."
roslaunch pioneer_description pioneer_kinect_sim.launch &
pid="$pid $!"
sleep 5s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
