#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Coord_sender"
roslaunch coords_sender coord_sender_one_robot_simple.launch  &
pid="$pid $!"
sleep 15s

echo "navigation_goal..."
roslaunch multi_nav send_goal.launch &
pid="$pid $!"
sleep 10s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
